apiVersion: v2
name: integrated-care
description: Helm chart for Integrated Care Platform (API + Data Pipeline Monitoring)
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: redis
    version: "20.6.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: dependencies.redis.enabled
  - name: kafka
    version: "30.1.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: dependencies.kafka.enabled
  - name: kube-prometheus-stack
    version: "65.8.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: dependencies.kubePrometheusStack.enabled
  - name: airflow
    version: "1.15.0"
    repository: "https://airflow.apache.org"
    condition: dependencies.airflow.enabled

