apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: integrated-care
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.template.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - pipeline-monitoring-deployment.yaml
  - pipeline-monitoring-service.yaml
  - servicemonitor.yaml

