apiVersion: v1
kind: Service
metadata:
  name: pipeline-monitoring
  namespace: integrated-care
  labels:
    app: pipeline-monitoring
spec:
  selector:
    app: pipeline-monitoring
  ports:
    - name: http
      port: 80
      targetPort: http

