{{- if .Values.authService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "integrated-care.fullname" . }}-auth-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "integrated-care.labels" . | nindent 4 }}
    app: auth-service
spec:
  type: {{ .Values.authService.service.type }}
  selector:
    app: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.service.targetPort }}
      {{- if and (eq .Values.authService.service.type "NodePort") .Values.authService.service.nodePort }}
      nodePort: {{ .Values.authService.service.nodePort }}
      {{- end }}
{{- end }}
