apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "integrated-care.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "integrated-care.labels" . | nindent 4 }}
data:
  API_HOST: {{ .Values.config.API_HOST | quote }}
  API_PORT: {{ .Values.config.API_PORT | quote }}
  API_CACHE_TTL_SECONDS: {{ .Values.config.API_CACHE_TTL_SECONDS | quote }}
  API_EVENT_TOPIC: {{ .Values.config.API_EVENT_TOPIC | quote }}
  API_EVENT_DLQ_TOPIC: {{ .Values.config.API_EVENT_DLQ_TOPIC | quote }}
  API_EVENT_PARKING_TOPIC: {{ .Values.config.API_EVENT_PARKING_TOPIC | quote }}
  API_EVENT_CONSUMER_GROUP: {{ .Values.config.API_EVENT_CONSUMER_GROUP | quote }}
  API_EVENT_CONSUMER_MAX_RETRIES: {{ .Values.config.API_EVENT_CONSUMER_MAX_RETRIES | quote }}
  API_EVENT_CONSUMER_BASE_DELAY_SECONDS: {{ .Values.config.API_EVENT_CONSUMER_BASE_DELAY_SECONDS | quote }}
  API_EVENT_DEDUP_TTL_SECONDS: {{ .Values.config.API_EVENT_DEDUP_TTL_SECONDS | quote }}
  API_EVENT_DLQ_RETRY_GROUP: {{ .Values.config.API_EVENT_DLQ_RETRY_GROUP | quote }}
  API_EVENT_DLQ_RETRY_MAX_ATTEMPTS: {{ .Values.config.API_EVENT_DLQ_RETRY_MAX_ATTEMPTS | quote }}
  API_EVENT_PARKING_MONITOR_GROUP: {{ .Values.config.API_EVENT_PARKING_MONITOR_GROUP | quote }}
  PARKING_ALERT_THRESHOLD: {{ .Values.config.PARKING_ALERT_THRESHOLD | quote }}
  PARKING_ALERT_WINDOW_SECONDS: {{ .Values.config.PARKING_ALERT_WINDOW_SECONDS | quote }}
  PARKING_ALERT_COOLDOWN_SECONDS: {{ .Values.config.PARKING_ALERT_COOLDOWN_SECONDS | quote }}
  PIPELINE_API_EVENT_PUBLISH_ENABLED: {{ .Values.config.PIPELINE_API_EVENT_PUBLISH_ENABLED | quote }}
  PIPELINE_MONITORING_HOST: {{ .Values.config.PIPELINE_MONITORING_HOST | quote }}
  PIPELINE_MONITORING_PORT: {{ .Values.config.PIPELINE_MONITORING_PORT | quote }}
  PIPELINE_STORE_BACKEND: {{ .Values.config.PIPELINE_STORE_BACKEND | quote }}
  PIPELINE_KAFKA_PUBLISH_ENABLED: {{ .Values.config.PIPELINE_KAFKA_PUBLISH_ENABLED | quote }}
  PIPELINE_PROVIDER_NAME: {{ .Values.config.PIPELINE_PROVIDER_NAME | quote }}
  PIPELINE_OUTPUT_FILE: {{ .Values.config.PIPELINE_OUTPUT_FILE | quote }}
  PIPELINE_PAGE_SIZE: {{ .Values.config.PIPELINE_PAGE_SIZE | quote }}
  PIPELINE_START_PAGE: {{ .Values.config.PIPELINE_START_PAGE | quote }}
  PIPELINE_END_PAGE: {{ .Values.config.PIPELINE_END_PAGE | quote }}
  AUTH_SERVICE_HOST: {{ .Values.config.AUTH_SERVICE_HOST | quote }}
  AUTH_SERVICE_PORT: {{ .Values.config.AUTH_SERVICE_PORT | quote }}
  USER_SERVICE_HOST: {{ .Values.config.USER_SERVICE_HOST | quote }}
  USER_SERVICE_PORT: {{ .Values.config.USER_SERVICE_PORT | quote }}
  FACILITY_SERVICE_HOST: {{ .Values.config.FACILITY_SERVICE_HOST | quote }}
  FACILITY_SERVICE_PORT: {{ .Values.config.FACILITY_SERVICE_PORT | quote }}
  SEARCH_SERVICE_HOST: {{ .Values.config.SEARCH_SERVICE_HOST | quote }}
  SEARCH_SERVICE_PORT: {{ .Values.config.SEARCH_SERVICE_PORT | quote }}
  ADMIN_SERVICE_HOST: {{ .Values.config.ADMIN_SERVICE_HOST | quote }}
  ADMIN_SERVICE_PORT: {{ .Values.config.ADMIN_SERVICE_PORT | quote }}
