{{- if .Values.pipelineMonitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "integrated-care.fullname" . }}-pipeline-monitoring
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "integrated-care.labels" . | nindent 4 }}
    app: pipeline-monitoring
spec:
  type: {{ .Values.pipelineMonitoring.service.type }}
  selector:
    app: pipeline-monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.pipelineMonitoring.service.port }}
      targetPort: http
{{- end }}

