{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "integrated-care.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "integrated-care.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: {{ include "integrated-care.redisUrl" . | quote }}
  DATABASE_URL: {{ include "integrated-care.databaseUrl" . | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ include "integrated-care.kafkaBootstrapServers" . | quote }}
  PARKING_ALERT_WEBHOOK_URL: {{ .Values.secret.PARKING_ALERT_WEBHOOK_URL | quote }}
  FACILITY_PROVIDER_BASE_URL: {{ .Values.secret.FACILITY_PROVIDER_BASE_URL | quote }}
  JWT_SECRET_KEY: {{ .Values.secret.JWT_SECRET_KEY | quote }}
  ENCRYPTION_MASTER_KEY: {{ .Values.secret.ENCRYPTION_MASTER_KEY | quote }}
  INTERNAL_EVENT_HMAC_SECRET: {{ .Values.secret.INTERNAL_EVENT_HMAC_SECRET | quote }}
{{- end }}
