{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "integrated-care.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "integrated-care.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: {{ .Values.secret.REDIS_URL | quote }}
  DATABASE_URL: {{ include "integrated-care.databaseUrl" . | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.secret.KAFKA_BOOTSTRAP_SERVERS | quote }}
  PARKING_ALERT_WEBHOOK_URL: {{ .Values.secret.PARKING_ALERT_WEBHOOK_URL | quote }}
  FACILITY_PROVIDER_BASE_URL: {{ .Values.secret.FACILITY_PROVIDER_BASE_URL | quote }}
{{- end }}
