{{- if .Values.userService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "integrated-care.fullname" . }}-user-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "integrated-care.labels" . | nindent 4 }}
    app: user-service
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-service
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: user-service
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "integrated-care.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: user-service
          image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
          imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.security.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.userService.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "integrated-care.fullname" . }}-config
            {{- if .Values.secret.create }}
            - secretRef:
                name: {{ include "integrated-care.fullname" . }}-secret
            {{- end }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.userService.resources | nindent 12 }}
{{- end }}

